language: php
sudo: true

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_install:
  - sudo apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node --version
  - npm install -g bower

before_script:
  - composer install
  - bower install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build

script:
  - phpunit
  - gulp --production
