language: php

notifications:
  email:
    on_success: never
    on_failure: change

slack:
  rooms:
    secure: "S0TqxJjgILshBUsdBZfgJpqh8HyW34L1VZD+K4d+rsEO6XqgPP1F0IsxGgghbRE3+VIkq9PBLye4b4W/ftZIWpJ5DXQa+qFPlPP5vftMILQDBydaXPUiVQMtVEUDBA0Ks0QNd46/aCnya8ICmswSTbm3PDgHnycTaMaonLD+Z7gxH9HGk4Wj84olHIbwAThvGsdVMKw0lJUiYuwsfYsZ4IPP1NOmOqeV9pB5UqOp5BPGTceKsJt1bFaWZ1NP4+WJuaPKMSQlTcxFxI42ja0X+bCcdUbLErnSmvD7hBbW34/UJAxNYqCrRupYNBf9NM7RwFYc72wO/p+EuGPCWQx78gUl/7g9aYhXYU7ld25EFcXUeI7rY0KV6GJuGpCOZZNVioURmJ7TwIu2fZuNbjlDL3EUfhkIVGe3W+K/DcwiqQG721Jh+vfYyO6hQvLWTqJPkXlnlZYlxzIKi9RjrZM8NDw0JeYERgb7IQROZuZ070kKx1fyGjjilTpwEkVSPvjzBlV2o2Wdnv0HQDTA8DD+W/X27nHDbQbx4ywHSBIJFvV6uGlsS3XzbULacShxYDEkZBJqm3kZpDrCIytmz7bj4pdM6aAWISS8Nt9luNiZq53ZOu3Eoc82C+Fh+KPK8CQb8Z8xMENG9JAWwSt6OBTbY2wrvhrZimtbCvMqI4LzGEw="

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1


before_install:

  - echo $TRAVIS_OS_NAME
  # node
  # ------------------------
  - export PATH=./node_modules/.bin/:$PATH
  - rm -rf ~/.nvm && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 4.0.0
  - nvm use 4

before_script:
  - npm install -g bower
  - composer install
  - bower install
  - npm install --loglevel error
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build

script:
  - phpunit
  - gulp --production
