sudo: false
language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - npm cache clean -f
  - npm install -g n
  - n stable
  - composer install
  - npm install -g bower
  - bower install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build

script:
  - phpunit
  - gulp --production
