language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - TRAVIS_NODE_VERSION="4"

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_install:
  - npm install -g npm
  - npm install -g bower
  - node -v

before_script:
  - composer install
  - bower install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build

script:
  - phpunit
  - gulp --production
