language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1


before_install:

  - echo $TRAVIS_OS_NAME
  # node
  # ------------------------
  - export PATH=./node_modules/.bin/:$PATH
  - rm -rf ~/.nvm && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 4.0.0
  - nvm use 4
  - node --version
  - npm --version
  - nvm --version

before_script:
  - npm install -g bower
  - composer install
  - bower install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build

script:
  - phpunit
  - gulp --production
